### ISSUE TITLE
[BUG]: 评论区没有显示IP属地

### ISSUE THREAD

**Issue by eeelester** [maxchang3/Bilibili-Web-Show-IP-Location#101]
### 脚本版本

1.6.3

### 浏览器

chrome：131.0.6778.205（正式版本） （64 位）

### 用户脚本管理器

Tampermonkey

### 出现问题的网址

https://t.bilibili.com/?spm_id_from=333.1365.0.0

### 描述现象

评论区没有显示IP属地

### 如何复现

1.进入b站首页
2.点击右上角动态，进入动态页面，此时路径为https://t.bilibili.com/?spm_id_from=333.1007.0.0
3.然后我调试发现有个地方好像不对，多了个感叹号
`/**
  单独动态页
 */
router.serve('https://t.bilibili.com/', async () => {
    const dynItem = await isElementLoaded('.bili-dyn-item')
    debugger
    const isNewDyn = !dynItem.querySelector('.bili-dyn-item__footer')
    if (isNewDyn) {
        hookLit()
    } else {
        hookBBComment()
    }
})`
看代码是应该进入hookLit的，但是因为`!dynItem.querySelector('.bili-dyn-item__footer') `多了个!结果为false了，就进入hookBBComment()，导致没有显示出IP属地。
想问下这是BUG吗？还是在哪个页面会因此来设计？

**Comment by maxchang3** [comment]
这应该和这个问题无关，`.bili-dyn-item__footer` 是旧版动态才会有的标识。  

请问你在访问 `https://t.bilibili.com/` 时，功能正常吗？  

如果正常，那可能是因为我用 `{ endsWith: '/' }` 来区分单独动态页和动态主页，但这里的 URL 并不是以 `/` 结尾，所以才会导致问题。  

另外，我平时安装了 `CleanURLs` 插件，它会自动去掉这种参数，因此没有遇到类似的问题。

**Comment by eeelester** [comment]
我这边是新版的（有“回到旧版”按钮），看了下也确实有这个样式...
直接访问 https://t.bilibili.com/ 没问题，但问题是从首页跳转过去就自带了后面的参数..

**Comment by maxchang3** [comment]
`.bili-dyn-item__footer` 是用于 `https://t.bilibili.com/1015183385215107107` 这种单独动态的，在动态主页这里用的是另一套逻辑。

带参数的问题，我在分流的时候把查询参数去掉就好了。

**Comment by eeelester** [comment]
1.我刚测试了下，关于`.bili-dyn-item__footer`是我看错了，动态主页的这个样式不是在评论区中。
2.OKOK

**Comment by maxchang3** [comment]
已经修复并发布，请尝试 v1.6.4
