### ISSUE TITLE
评论区IP和动态评论区IP显示未知

### ISSUE THREAD

**Issue by Miku2563** [maxchang3/Bilibili-Web-Show-IP-Location#24]
评论区IP和动态评论区IP显示未知,win10 x64   谷歌浏览器最新  121.0.6167.185（正式版本） （64 位） 和
edge  121.0.2277.128 (正式版本) (64 位) 最新都出现这个问题，试过降级，重装，换视频，都无效
![2 (1)](https://github.com/maxchang3/Bilibili-Web-Show-IP-Location/assets/92353453/4441087e-da96-4084-be50-cd08296565e3)
![2 (2)](https://github.com/maxchang3/Bilibili-Web-Show-IP-Location/assets/92353453/769ae6f1-6a8c-45d8-a55e-8a812869afc7)

**Comment by Miku2563** [comment]
1.5.5的

**Comment by Miku2563** [comment]
浏览器控制台 
![4$Y3`NCLS62_NT2XY 4 75](https://github.com/maxchang3/Bilibili-Web-Show-IP-Location/assets/92353453/22694212-5b63-486a-936b-75cb279595f2)

**Comment by maxchang3** [comment]
评论元素下面没法获取 context 了，我研究下先~

**Comment by Miku2563** [comment]
oo

**Comment by maxchang3** [comment]
目前，通过一个变通办法暂时修复了。可能存在一些问题。

**Comment by Miku2563** [comment]
ok

**Comment by maxchang3** [comment]
https://github.com/maxchang3/Bilibili-Web-Show-IP-Location/releases/download/v1.5.8-beta.0/bilibili-web-show-ip-location.user.js

可以试试 beta 版，换了个工作方式，不知道是不是我的原因，可能需要重启一下浏览器 / 清除缓存。 目前试了下还挺稳定

**Comment by maxchang3** [comment]
> ok

直接更最新的正式版就可以了😘
