### ISSUE TITLE
使用 Map 匹配 URL 前缀

### ISSUE THREAD

**Issue by maxchang3** [maxchang3/Bilibili-Web-Show-IP-Location#35]
目前使用遍历循环匹配，大部分匹配逻辑都是先匹配 URL 的前缀，因此完全可以使用 URL 前缀作为 Map 的 Key 直接以 $O(1)$ 获取对应路由函数。但是这样会失去一些灵活性。

**Comment by Lilpiggie0522** [comment]
哥，我想请问你这个原理是什么啊，我看了看你代码发现你是等页面渲染完成以后通过监听评论html元素的某些属性来获取b站保存的评论ip地址？我也想写个差不多的，不知道能不能给点建议，我纯小白大二学生，就会点前端(react, nextJs)和后端(java, nodejs, springboot) 该怎么开始啊?

**Comment by maxchang3** [comment]
你好！

你说的原理基本上是对的。不过由于 B 站前段时间的更新，实际获取数据的细节变得更复杂了。具体情况我在 README 中有阐述。

写这类脚本的关键是要对 JavaScript 或其框架进行逆向工程。例如，了解数据是如何挂载到 DOM 上的、如何在现有页面上打断点进行调试、熟悉框架的生命周期和渲染流程等。主要来说就是前端的知识了。

其实，这个脚本的原理相对简单。最开始的时候，我通过调试发现了挂载在 DOM 节点上的数据。后来，由于更新原因，这种方法行不通了，于是我使用了一个现成的 [库](https://greasyfork.org/zh-CN/scripts/449444-hook-vue3-app) 来暴露这些数据。既然你学过 React，应该也能了解到数据 VDOM 和数据挂载之类的流程。

关于如何开始，我并没有特别系统地学习过。不过，前段时间我发现油猴中文网社区的建设还不错，并且上面有一些 [比较系统的教程](https://greasyfork.org/zh-CN/scripts/449444-hook-vue3-app)，你可以参考一下。你也可以尝试从一个具体的需求出发，试试能不能做出来，我最开始也是这样来的。
