### ISSUE TITLE
貌似个人主页的ip不能正常显示？

### ISSUE THREAD

**Issue by luozhlun** [maxchang3/Bilibili-Web-Show-IP-Location#53]

**Comment by maxchang3** [comment]
个人主页的 IP 属地属于 APP 端的接口，需要单独鉴权，目前暂不支持。README 已说明。

**Comment by maxchang3** [comment]
由于个人主页 IP 属地需要使用 APP 接口，依赖于许多额外逻辑，目前单独实现了一个脚本，如有需要请前往 [Greasy Fork](https://greasyfork.org/scripts/534807) 或 [Github(maxchang3/userscripts)](https://github.com/maxchang3/userscripts/blob/main/BiliSpaceIPLocator/README.md) 安装。
