### ISSUE TITLE
2024.07.04发现所有评论均无法显示IP归属地

### ISSUE THREAD

**Issue by AdeSpike** [maxchang3/Bilibili-Web-Show-IP-Location#63]
今天发现插件无法显示任何评论的IP地址，是B站更换接口还是前端网页结构发生变化了吗？
![Pic](https://github.com/maxchang3/Bilibili-Web-Show-IP-Location/assets/46109115/d74d2996-67fa-4597-bf0c-05faa5634bdf)

**Comment by maxchang3** [comment]
似乎有新版本测试，但是目前我两个账号都没有出现。我还在想怎么调试。

**Comment by maxchang3** [comment]
@Nevidebla 好的，等我修复

**Comment by maxchang3** [comment]
@Nevidebla 已经修复了
