### ISSUE TITLE
新版本有问题，导致用户信息和评论无法加载

### ISSUE THREAD

**Issue by cikichen** [maxchang3/Bilibili-Web-Show-IP-Location#64]
![image](https://github.com/maxchang3/Bilibili-Web-Show-IP-Location/assets/1478821/94dda22a-86fa-4aa5-bf21-07901ff52c44)

除了视频，其他信息全部加载不了

**Comment by LeYuanBH** [comment]
我是连视频都加载不出来，必须关闭插件才能正常

**Comment by maxchang3** [comment]
[bilibili-web-show-ip-location.user.zip](https://github.com/user-attachments/files/16118269/bilibili-web-show-ip-location.user.zip)

试下这个版本有没有区别。 没有的话要等待修改了

**Comment by LeYuanBH** [comment]
> [bilibili-web-show-ip-location.user.zip](https://github.com/user-attachments/files/16118269/bilibili-web-show-ip-location.user.zip)
> 
> 试下这个版本有没有区别。没有的话要等待修改了

还是不行，还是等修改好后吧

**Comment by cikichen** [comment]
> > [bilibili-web-show-ip-location.user.zip](https://github.com/user-attachments/files/16118269/bilibili-web-show-ip-location.user.zip)
> > 试下这个版本有没有区别。没有的话要等待修改了
> 
> 还是不行，还是等修改好后吧

https://update.greasyfork.org/scripts/494784/bilibili%20reply-location%20enable.meta.js

这个目前可用

**Comment by maxchang3** [comment]
根据 GreasyFork 上的[讨论](https://greasyfork.org/zh-CN/scripts/466815/discussions/250445) 简单修改了一下逻辑。如果有时间麻烦请帮忙测试一下最新版本（1.5.17），由于最近的时间原因我没法做太大幅的修改。 上面的脚本通过 hook fetch 再修改元素也是个不错的方案。

**Comment by maxchang3** [comment]
目前根据u GreasyFork 上的反馈，应该已经修复。

**Comment by cikichen** [comment]
> 目前根据 GreasyFork 上的反馈，应该已经修复。

做好异常处理，即时脚本失效也不要影响正常的页面

**Comment by maxchang3** [comment]
> > 目前根据 GreasyFork 上的反馈，应该已经修复。
> 
> 
> 
> 做好异常处理，即时脚本失效也不要影响正常的页面

好的👌当时没考虑太多
